/**
 * reflex install-pi — Pi auto-mode pre-action hook.
 *
 * Returns a JSON decision that Pi can consume to Allow / Ask / Block
 * before executing a command or applying an edit.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { classifyCommand } from './classify-command.js';
import { classifyEdit, loadFragileMap } from './classify-edit.js';
import { logEvent } from './events.js';

export type PiHookDecision = 'allow' | 'ask' | 'block' | 'defer';

export type PiHookResult = {
  decision: PiHookDecision;
  reason: string;
  riskLevel: string;
  signals?: string[];
  warnings?: string[];
  testPlan?: string[];
  hookVersion: string;
};

const HOOK_VERSION = '0.1.0';

/**
 * Install the reflex hook into a repo's pi config.
 * Writes / updates .pi/settings.json to include the reflex hook path.
 */
export function installPiHook(repoDir: string): { installed: boolean; path: string } {
  const piDir = path.join(repoDir, '.pi');
  if (!fs.existsSync(piDir)) {
    fs.mkdirSync(piDir, { recursive: true });
  }

  const settingsPath = path.join(piDir, 'settings.json');
  let settings: { packages?: string[]; hooks?: Record<string, string> } = {};
  if (fs.existsSync(settingsPath)) {
    try {
      settings = JSON.parse(fs.readFileSync(settingsPath, 'utf8'));
    } catch {
      settings = {};
    }
  }

  settings.packages = settings.packages || [];
  if (!settings.packages.includes('./.repo-arch/reflex/pi-hook.js')) {
    settings.packages.push('./.repo-arch/reflex/pi-hook.js');
  }

  fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf8');
  return { installed: true, path: settingsPath };
}

/**
 * Generate the pre-action hook JS file for Pi auto mode.
 * This file is what gets loaded into Pi's hook system.
 */
export function writePiHookFile(repoDir: string): string {
  const hookDir = path.join(repoDir, '.repo-arch', 'reflex');
  if (!fs.existsSync(hookDir)) {
    fs.mkdirSync(hookDir, { recursive: true });
  }

  const hookCode = `/**
 * Pi pre-action hook — generated by repo-arch reflex
 * Auto-mode: allow / ask / block based on reflex classify
 */
import { classifyCommand } from './classify-command.js';
import { classifyEdit, loadFragileMap } from './classify-edit.js';
import { logEvent } from './events.js';

const REPO_DIR = '${repoDir.replace(/'/g, "\\'")}';
const HOOK_VERSION = '0.1.0';

/** @type {import('./install-pi').PiHookDecision} */
export async function beforeCommand(command, context) {
  const decision = classifyCommand(command);

  logEvent(REPO_DIR, 'pi_hook_triggered', { command, context }, { sessionId: context?.sessionId });

  if (decision.decision === 'block') {
    logEvent(REPO_DIR, 'pi_hook_decision', { decision: 'block', reason: decision.reason }, { sessionId: context?.sessionId });
    return { decision: 'block', reason: decision.reason, riskLevel: decision.riskLevel, hookVersion: HOOK_VERSION };
  }

  if (decision.decision === 'ask') {
    return { decision: 'ask', reason: decision.reason, riskLevel: decision.riskLevel, hookVersion: HOOK_VERSION };
  }

  logEvent(REPO_DIR, 'command_allowed', { command, decision: 'allow' }, { sessionId: context?.sessionId });
  return { decision: 'allow', reason: decision.reason, riskLevel: decision.riskLevel, hookVersion: HOOK_VERSION };
}

export async function beforeEdit(filePath, diff, context) {
  const fragileMap = loadFragileMap(REPO_DIR);
  const decision = classifyEdit(filePath, REPO_DIR, fragileMap);

  logEvent(REPO_DIR, 'edit_classified', { filePath, riskLevel: decision.riskLevel, signals: decision.signals }, { sessionId: context?.sessionId });

  if (decision.riskLevel === 'critical') {
    return { decision: 'block', reason: decision.reason, riskLevel: 'critical', warnings: decision.warnings, hookVersion: HOOK_VERSION };
  }

  if (decision.riskLevel === 'high') {
    return { decision: 'ask', reason: decision.reason, riskLevel: 'high', warnings: decision.warnings, testPlan: decision.testRecommendations, hookVersion: HOOK_VERSION };
  }

  return { decision: 'allow', reason: decision.reason, riskLevel: decision.riskLevel, hookVersion: HOOK_VERSION };
}
`;

  const hookPath = path.join(hookDir, 'pi-hook.js');
  fs.writeFileSync(hookPath, hookCode, 'utf8');

  const tsPath = path.join(hookDir, 'pi-hook.ts');
  fs.writeFileSync(tsPath, hookCode.replace('export async function', '// @ts-check\nexport async function'), 'utf8');

  return hookPath;
}

/**
 * Run the full install: write hook file + update pi settings.
 */
export function runInstallPi(repoDir: string): PiHookResult {
  const hookPath = writePiHookFile(repoDir);
  const { installed, path: settingsPath } = installPiHook(repoDir);

  return {
    decision: installed ? 'allow' : 'defer',
    reason: installed
      ? `reflex hook installed at ${hookPath}, settings at ${settingsPath}`
      : 'failed to install',
    riskLevel: 'low',
    hookVersion: HOOK_VERSION,
  };
}